server {
    listen 0.0.0.0:${PORT};  # Usa la variabile di ambiente PORT fornita da Render
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    # Indirizza tutte le richieste verso /api a index.php nella directory /api
    location /api {
        root /var/www/html; # Assicurati che punti alla directory corretta
        try_files $uri /api/index.php?$query_string;
    }

    # Configurazione per eseguire file PHP
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
